name: Run MACD Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install requests pyTelegramBotAPI

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
